<div id="app-loader" class="valign-wrapper">
    <div style="max-width: 500px; margin: 0 auto">
        <div style="max-width: 300px; margin: 0 auto">
            <img class="responsive-img" alt="PhpUnitGen"
                 src="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/logo.svg?sanitize=true">
            <div class="progress orange lighten-5">
                <div class="indeterminate orange"></div>
            </div>
        </div>
        <h5>PhpUnitGen is loading, please wait.</h5>
    </div>
</div>

<?php include __DIR__ . '/partial/mobile.phtml'; ?>

<div id="global">

    <?php include __DIR__ . '/../layout/partial/nav.phtml'; ?>

    <main class="valign-wrapper">

        <div class="had-container center-align">

            <?php include __DIR__ . '/section/tab-main.phtml'; ?>

            <?php include __DIR__ . '/section/tab-code-editor.phtml'; ?>

            <?php include __DIR__ . '/section/tab-tests-editor.phtml'; ?>

        </div>

        <?php include __DIR__ . '/modal/documentation.phtml'; ?>

        <?php include __DIR__ . '/modal/configuration.phtml'; ?>

        <?php include __DIR__ . '/modal/confirm-reset.phtml'; ?>

        <?php include __DIR__ . '/partial/floating-button.phtml'; ?>

    </main>

    <?php include __DIR__ . '/partial/spinner.phtml'; ?>

    <?php include __DIR__ . '/../layout/partial/footer.phtml'; ?>

</div>

