<footer class="page-footer">
    <div class="footer-copyright blue">
        <div class="container">
            <div class="row valign-wrapper" style="margin: 0">
                <div class="col s12 m8">
                    Copyright &copy; 2017-<?= date('Y') ?>
                    <a class="white-text" href="https://github.com/paul-thebaud" target="_blank"><b>Paul Thébaud</b></a>
                    (<a class="white-text" href="https://github.com/paul-thebaud/phpunit-generator"
                        target="_blank"><b>PhpUnitGen</b></a> version <?= \PhpUnitGen\Console\Application::VERSION ?>).
                </div>
                <div class="col s12 m4 right-align">
                    <a href="#modal-legal" class="white-text modal-trigger"><b>Legal and terms of use</b></a>
                </div>
            </div>
        </div>
    </div>
</footer>
