<nav class="blue">
    <div class="nav-wrapper container">
        <?php if (!isset($isApp)): ?>
        <ul class="left hide-on-large-only">
            <li>
                <a href="#" id="btn-sidenav" data-activates="slide-out" class="button-collapse show-on-large">
                    <i class="material-icons">menu</i>
                </a>
            </li>
        </ul>
        <?php endif; ?>
        <a href="<?= $this->getAttribute(\PhpUnitGen\Website\Middleware\ResourceMiddleware::RESOURCE_APP) ?>"
           class="brand-logo valign-wrapper center">
            <img class="responsive-img" alt="PhpUnitGen"
                 src="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/light_logo.svg?sanitize=true">
        </a>
        <?php if (isset($isApp)): ?>
        <ul class="right">
                <li>
                    <a href="#modal-configuration" class="modal-trigger">
                        <i class="material-icons left">settings</i><span class="hide-on-small-only">Settings</span>
                    </a>
                </li>
        </ul>
        <?php endif; ?>
    </div>
</nav>
