<h3>About PhpUnitGen</h3>

<p>
    PhpUnitGen est un outil de développement <b>en ligne</b> ou dans un <b>terminal</b>
    permettant de générer les squelettes de vos tests unitaires en PHP.
    Il utilise <i>PHPUnit 7</i> et <i>PHP 7.1</i>.
    <br>
    <br>
    Ce projet open source a commencé durant l'<b>été 2017</b>.
    <br>
    <br>
    Depuis la sortie de la version 2.x.x, quelques personnes commencent à parler de PhpUnitGen.
    <br>
    Voici les articles concernant le projet:
</p>
<ul class="browser-default">
    <li>
        <a href="https://dev.to/paulthebaud/phpunitgen-simplify-the-writing-of-your-unit-tests--4nec" target="_blank">
            Un article sur dev.to, écrit par Paul Thébaud [EN]
            <sup><i class="material-icons tiny">open_in_new</i></sup>
        </a>
    </li>
    <li>
        <a href="https://doc.phpunitgen.local/fr/about.html">
            Le même article, en version française [FR]
        </a>
    </li>
</ul>
<div class="card blue lighten-2">
    <div class="card-content">
        <h5><i class="material-icons left">info</i>Note</h5>
        <p>
            Si vous aimez PhpUnitGen, partagez-le !
        </p>
    </div>
</div>
