    <img class="responsive-img" style=""
         src="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/example.png">
    <span class="card-title">PhpUnitGen, simplifier l'écriture de vos tests unitaires !</span>

    <p>Vous faites partie du club très fermé des developpeurs <em>PHP</em><br>
        et vous vous infligez des tourbillons de copier/coller<br>
        pour satisfaire <em>PHPUnit</em> ?<br>
        Les tests unitaires vous hantent jusque dans vos cauchemars ?</p>

    <p><strong>PhpUnitGen</strong> a été conçu pour rendre vos nuits plus douces et vos applications mieux testées !</p>

    <p class="center-align">
        <img src="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/logo.svg?sanitize=true" width="200px">
    </p>

    <p><strong>PhpUnitGen</strong> est un outil de développement <strong>en ligne</strong> ou <strong>dans un terminal</strong>, permettant de <strong>générer des squelettes de tests unitaires</strong> pour du code <em>PHP</em>.</p>

    <h4>Pourquoi PhpUnitGen ?</h4>

    <p>
        Comme tout le monde, je dois travailler pour manger et manger pour travailler (même si l'informatique est une passion hein).<br>
        J'avais déjà un arrière goût de boucle dans la bouche, et mon travail était de tester une application PHP.<br>
        Qu'y a-t-il de plus ennuyeux et inintéressant que de recréer encore un squelette de tests pour un énième fichier <em>PHP</em> ? Une course de F1 peut-être ...
    </p>

    <p>
        Partant de ce postulat, je me suis surpris à vouloir "féliciter" le génie<br>
        qui réussirait à générer automatiquement toutes mes bases et squelettes de tests unitaires et ainsi me ferait gagner énormément de temps.
    </p>

    <p>
        J'ai alors modestement créé cet outil.<br>
        <strong>PhpUnitGen</strong> était né.
    </p>

    <p>
        Je me suis ensuite dit qu'il fallait peut-être mettre à profit le temps gagné, plutôt que de le passer devant Netflix, et j'ai publié l'outil en <strong>open source</strong>.
    </p>

    <h4>Qu'est-ce que PhpUnitGen ?</h4>

    <p><strong>PhpUnitGen</strong> est d'un outil de développement, programmé en <em>PHP7.1</em>, qui permet de générer des squelettes de tests unitaires à partir d'un code source <em>PHP</em>.</p>

    <p>Les tests générés sont écrits en <em>PHP7.1</em> et pour fonctionner avec <em>PHPUnit 6 / 7</em>.</p>

    <p>Voici quelques-unes des <strong>fonctionnalités</strong> de <strong>PhpUnitGen</strong> :</p>

    <ul class="browser-default">
        <li>Il <strong>détecte automatiquement</strong> les <em>classes</em>, les <em>traits</em> ou autres formats et les instantie de manière adaptée.</li>
        <li>Il permet de <strong>générer automatiquement</strong> des tests pour les méthodes <em>getter</em> / <em>setter</em>.</li>
        <li>Il propose de nombreuses <strong>annotations</strong>, permettant de créer automatiquement des tests simples, des <em>mocks</em> ou encore des instantiations de <em>classes</em>.</li>
    </ul>

    <h4>Comment l'utiliser ?</h4>

    <p>Il y a plusieurs manières d'utiliser <strong>PhpUnitGen</strong>.</p>

    <p>Via l'application web (<strong>open source</strong>) : <a href="https://phpunitgen.io">phpunitgen.io</a>.</p>

    <p>Via le package <em>Composer</em> qui s'utilise avec un <strong>terminal</strong> (également <strong>open source</strong>) : <a href="https://github.com/paul-thebaud/phpunit-generator">paulthebaud/phpunit-generator</a>.</p>

    <h4>Comment aider à améliorer PhpUnitGen ?</h4>

    <p>Vous pouvez aider à améliorer <strong>PhpUnitGen</strong> en envoyant toutes vos remarques / bugs via les issues sur <a href="https://github.com/paul-thebaud/phpunit-generator/issues">Github</a>.</p>

    <p>Vous pouvez aussi partager le lien de cet article, du package ou de l'application web !</p>

    <p><strong>Merci de votre lecture, et à bientôt !</strong></p>

    <a href="https://dev.to/paulthebaud/phpunitgen-simplify-the-writing-of-your-unit-tests--4nec">Lien de l'article original en anglais</a>
