    <img class="responsive-img" style=""
         src="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/example.png">
    <span class="card-title">PhpUnitGen, simplifier l'écriture de vos tests unitaires !</span>

    <p>Vous faites partie du club très fermé des developpeurs <i>PHP</i><br>
        et vous vous infligez des tourbillons de copier/coller<br>
        pour satisfaire <i>PHPUnit</i> ?<br>
        Les tests unitaires vous hantent jusque dans vos cauchemars ?</p>

    <p><b>PhpUnitGen</b> a été conçu pour rendre vos nuits plus douces et vos applications mieux testées !</p>

    <p class="center-align">
        <img src="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/logo.svg?sanitize=true" width="200px">
    </p>

    <p><b>PhpUnitGen</b> est un outil de développement <b>en ligne</b> ou <b>dans un terminal</b>, permettant de <b>générer des squelettes de tests unitaires</b> pour du code <i>PHP</i>.</p>

    <h4>Pourquoi PhpUnitGen ?</h4>

    <p>
        Comme tout le monde, je dois travailler pour manger et manger pour travailler (même si l'informatique est une passion hein).<br>
        J'avais déjà un arrière goût de boucle dans la bouche, et mon travail était de tester une application PHP.<br>
        Qu'y a-t-il de plus ennuyeux et inintéressant que de recréer encore un squelette de tests pour un énième fichier <i>PHP</i> ? Une course de F1 peut-être ...
    </p>

    <p>
        Partant de ce postulat, je me suis surpris à vouloir "féliciter" le génie<br>
        qui réussirait à générer automatiquement toutes mes bases et squelettes de tests unitaires et ainsi me ferait gagner énormément de temps.
    </p>

    <p>
        J'ai alors modestement créé cet outil.<br>
        <b>PhpUnitGen</b> était né.
    </p>

    <p>
        Je me suis ensuite dit qu'il fallait peut-être mettre à profit le temps gagné, plutôt que de le passer devant Netflix, et j'ai publié l'outil en <b>open source</b>.
    </p>

    <h4>Qu'est-ce que PhpUnitGen ?</h4>

    <p><b>PhpUnitGen</b> est d'un outil de développement, programmé en <i>PHP7.1</i>, qui permet de générer des squelettes de tests unitaires à partir d'un code source <i>PHP</i>.</p>

    <p>Les tests générés sont écrits en <i>PHP7.1</i> et pour fonctionner avec <i>PHPUnit 6 / 7</i>.</p>

    <p>Voici quelques-unes des <b>fonctionnalités</b> de <b>PhpUnitGen</b> :</p>

    <ul class="browser-default">
        <li>Il <b>détecte automatiquement</b> les <i>classes</i>, les <i>traits</i> ou autres formats et les instantie de manière adaptée.</li>
        <li>Il permet de <b>générer automatiquement</b> des tests pour les méthodes <i>getter</i> / <i>setter</i>.</li>
        <li>Il propose de nombreuses <b>annotations</b>, permettant de créer automatiquement des tests simples, des <i>mocks</i> ou encore des instantiations de <i>classes</i>.</li>
    </ul>

    <h4>Comment l'utiliser ?</h4>

    <p>Il y a plusieurs manières d'utiliser <b>PhpUnitGen</b>.</p>

    <p>Via l'application web (<b>open source</b>) : <a href="https://phpunitgen.io">phpunitgen.io</a>.</p>

    <p>Via le package <i>Composer</i> qui s'utilise avec un <b>terminal</b> (également <b>open source</b>) : <a href="https://github.com/paul-thebaud/phpunit-generator">paulthebaud/phpunit-generator</a>.</p>

    <h4>Comment aider à améliorer PhpUnitGen ?</h4>

    <p>Vous pouvez aider à améliorer <b>PhpUnitGen</b> en envoyant toutes vos remarques / bugs via les issues sur <a href="https://github.com/paul-thebaud/phpunit-generator/issues">Github</a>.</p>

    <p>Vous pouvez aussi partager le lien de cet article, du package ou de l'application web !</p>

    <p><b>Merci de votre lecture, et à bientôt !</b></p>

    <a href="https://dev.to/paulthebaud/phpunitgen-simplify-the-writing-of-your-unit-tests--4nec">Lien de l'article original en anglais</a>
