<h3>PhpUnitGen</h3>

<?php include __DIR__ . '/../partial/badges.phtml'; ?>

<h3>Documentation française</h3>

<div class="card orange lighten-2">
    <div class="card-content">
        <h5><i class="material-icons left">warning</i>Note</h5>
        <p>
            <b>N'OUBLIEZ PAS</b> de vérifier les tests générés ! PhpUnitGen
            vous indiquera les endroits à vérifier ou à compléter avec de multiples
            annotations <i>PHPDoc</i> <code>@todo</code>.
        </p>
    </div>
</div>

<p>
    <b>Bonjour !</b>
    <br>
    <br>
    Bienvenue sur la <b>documentation française</b> de PhpUnitGen.
    <br>
    <br>
    Vous pouvez trouver de <b>nombreuses informations</b> ici !
</p>
<ul class="browser-default">
    <li>Une page "<b>à propos</b>" contenant des informations ou des articles concernant PhpUnitGen.</li>
    <li>Une courte documentation sur l'utilisation de l'<b>application web</b>.</li>
    <li>Une documentation sur l'utilisation en <b>ligne de commandes<b/> (avec le package <i>Composer</i>).</li>
    <li>Une documentation sur l'utilisation avec du <b>code PHP</b> (avec le package <i>Composer</i>).</li>
    <li>Une documentation sur l'utilisation des <b>annotations</b> que propose PhpUnitGen.</li>
</ul>
<p>
    <b>Regardez les liens sur la gauche (en haut sur mobile), bonne lecture !</b>
</p>
<br>
<p>
    Quelques liens utiles :
</p>
<ul class="browser-default">
    <li>
        <a href="https://github.com/paul-thebaud/phpunit-generator" target="_blank">
            Lien du package Composer <sup><i class="material-icons tiny">open_in_new</i></sup>
        </a>
    </li>
    <li>
        <a href="https://github.com/paul-thebaud/phpunit-generator-website" target="_blank">
            Lien du code source de l'application web <sup><i class="material-icons tiny">open_in_new</i></sup>
        </a>
    </li>
</ul>
<br>
<br>
<p class="center-align" style="font-weight: bold">
    <a href="https://github.com/paul-thebaud/phpunit-generator/stargazers" target="_blank">
        Vous voulez aider ? Mettez une étoile sur le projet Github !
        <sup><i class="material-icons tiny">open_in_new</i></sup>
    </a>
</p>
