<h3>Installation</h3>

<p>
    La meilleure façon d'installer PhpUnitGen est via <i>Composer</i>.
    Cela permettra d'effectuer facilement les mises à jour.
    <br>
    <i>Composer</i> est le gestionnaire de package pour les projets PHP.
</p>

<pre><code class="bash language-bash">
$ composer require --dev paulthebaud/phpunit-generator ^2.0
</code></pre>
<br>
<p>
    L'option <code>--dev</code> est utilisé pour installer le package uniquement dans un environnement de développement.
    <br>
    PhpUnitGen utilise <i>PHP 7.1</i>, mais est aussi compatible (et testé avec <i>Travis</i>) avec <i>PHP 7.2</i>.
</p>

<h4>Etape suivante</h4>

<p>
    Maintenant que vous savez comment installer PhpUnitGen,
    <a href="/<?= $language ?>/terminal.html">apprenez à l'utiliser via la ligne de commande</a>.
</p>
