<h3>Application web</h3>

<p>
    PhpUnitGen est utilisable <b>en ligne</b>, car il analyse le code PHP plutôt
    que d'utiliser les Reflections PHP.
    <br>
    <br>
    Comme de nombreux outils, il est <b>configurable</b> dans son fonctionnement ou son design.
    <br>
    <b>Grâce au bouton de configuration</b> - en haut à droite lorsque vous êtes sur l'application -
    vous pouvez modifier ces paramètres :
</p>
<ul class="browser-default">
    <li><b>Taille de l'éditeur</b> : permet de régler la hauteur de l'éditeur de code PHP.</li>
    <li><b>Thème</b> : permet de changer les couleurs de l'application (en plus il y a des surprises quand vous utilisez l'application 🦄).</li>
    <li><b>Generation automatique</b> : permet de générer automatiquement les tests unitaires des méthodes getters / setters, ou l'instanciation des classes ou traits.</li>
    <li><b>Analyse des méthodes privées / protégées</b> : permet d'activer ou de désactiver la génération de squelettes pour les méthodes privées ou protégées.</li>
    <li><b>Analyse des interfaces</b> : permet d'activer ou de désactiver la génération de squelettes pour les interfaces PHP.</li>
    <li><b>PHPDoc des tests générés</b> : permet de gérer une liste des annotations <i>PHPDoc</i> (<code>@author</code> par exemple) qui se trouveront dans l'entête de la classe de test.</li>
</ul>
<div class="card blue lighten-2">
    <div class="card-content">
        <h5><i class="material-icons left">info</i>Note</h5>
        <p>
            Cette configuration sera <b>automatiquement sauvegarder</b> à chaque modification, directement dans le <b>stockage
                de votre navigateur</b>.
            Il est possible de la <b>réinitialiser avec le bouton "reset"</b>, en bas à gauche de la page de configuration.
        </p>
    </div>
</div>
<br>
<p>
    L'application web peut ensuite être utilisé de deux manières différentes :
</p>
<ul class="browser-default">
    <li>Soit vous <b>importez un fichier PHP</b>.</li>
    <li>Soit vous utilisez l'<b>éditeur de code PHP</b> à votre disposition (n'oubliez pas que vous pouvez founir le <b>nom qu'aura la classe générée</b>, dans le <b>champs au dessus de l'éditeur</b>).</li>
</ul>
<br>
<p>
    Enfin, lorsque vous êtes <b>sur cette documentation</b>, vous pouvez juste cliquez sur le <b>bouton en bas à droite</b>
    pour aller sur l'<b>application PhpUnitGen</b>.
</p>

<h4>Etape suivante</h4>

<p>
    Maintenant que vous savez utilisez PhpUnitGen sur l'application web,
    <a href="/<?= $language ?>/annotations.html">apprenez en plus sur les annotations PhpUnitGen</a>.
</p>
