<div id="modal-confirm-reset" class="modal">
    <div class="modal-content">
        <h4>Your confirmation is required!</h4>
        <p>Are you sure you want to reset your configuration ?</p>
    </div>
    <div class="modal-footer">
        <button type="button" id="btn-confirm-reset" class="modal-action modal-close btn waves-effect waves-light red">
            Confirm
        </button>
        <button type="button" class="modal-action modal-close btn waves-effect waves-light">Close</button>
    </div>
</div>