<div id="modal-configuration" class="modal">
    <div class="modal-content">
        <h4 class="valign-wrapper"><i class="small material-icons left">settings</i>Settings</h4>

        <p>The PhpUnitGen configuration is saved in your web browser local storage.</p>
        <ul class="configuration-categories">

            <li class="configuration-category">
                <span class="configuration-category-title">
                    Appearance
                </span>
                <ul class="configuration-category-settings">
                    <li class="configuration-setting">
                        <div class="row valign-wrapper">
                            <div class="col s6">
                                <span>Editor height</span>
                            </div>
                            <div class="col s6">
                                <div class="input-field">
                                    <select name="height">
                                        <option value="300px">300px</option>
                                        <option value="500px">500px</option>
                                        <option value="700px">700px</option>
                                        <option value="1000px">1000px</option>
                                        <option value="1500px">1500px</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="configuration-setting">
                        <div class="row valign-wrapper">
                            <div class="col s6">
                                <span>Application theme</span>
                            </div>
                            <div class="col s6">
                                <div class="input-field">
                                    <select name="theme">
                                        <option value="light" class="circle left"
                                                data-icon="assets/img/light.jpg">Light theme</option>
                                        <option value="dark" class="circle left"
                                                data-icon="assets/img/dark.jpg">Dark theme</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </li>

            <li class="configuration-category">
                <span class="configuration-category-title">
                    PhpUnitGen configuration
                </span>
                <ul class="configuration-category-settings">
                    <li class="configuration-setting">
                        <div class="row valign-wrapper">
                            <div class="col s6">
                                <span>Automatic generation</span>
                            </div>
                            <div class="col s6">
                                <div class="switch">
                                    <label>
                                        <input name="auto" type="checkbox">
                                        <span class="lever"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="configuration-setting">
                        <div class="row valign-wrapper">
                            <div class="col s6">
                                <span>Private / protected methods parsing</span>
                            </div>
                            <div class="col s6">
                                <div class="switch">
                                    <label>
                                        <input name="private" type="checkbox">
                                        <span class="lever"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="configuration-setting">
                        <div class="row valign-wrapper">
                            <div class="col s6">
                                <span>Interfaces parsing</span>
                            </div>
                            <div class="col s6">
                                <div class="switch">
                                    <label>
                                        <input name="interface" type="checkbox">
                                        <span class="lever"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </li>

            <li class="configuration-category">
                <span class="configuration-category-title">
                    Generated tests class PHPDoc
                </span>
                <ul class="configuration-category-settings">
                    <li class="configuration-setting">
                        <div class="row valign-wrapper">
                            <div class="input-field col s4">
                                <input placeholder="@author" id="annotation" name="annotation" type="text">
                                <label for="annotation">Annotation tag</label>
                            </div>
                            <div class="input-field col s6">
                                <input placeholder="John Doe <john.doe@example.com>" id="content" name="content"
                                       type="text">
                                <label for="content">Annotation content</label>
                            </div>
                            <div class="col s2">
                                <button type="button" id="btn-annotation-add"
                                        class="btn waves-effect waves-light right">
                                    <i class="material-icons">add</i>
                                </button>
                            </div>
                        </div>
                        <div id="annotations-list"></div>
                    </li>
                </ul>
            </li>

        </ul>
    </div>
    <div class="modal-footer">
        <button type="button" class="modal-action modal-close btn waves-effect waves-light modal-trigger red left"
                data-target="modal-confirm-reset">Reset
        </button>
        <button type="button" class="modal-action modal-close btn waves-effect waves-light">Close</button>
    </div>
</div>