<div id="modal-documentation" class="modal modal-fixed-footer">
    <div class="modal-content">
        <h4>Documentation</h4>
        <div class="content">
            <p>Please wait until the documentation is full loaded...</p>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="modal-action modal-close btn waves-effect waves-light">Close</button>
    </div>
</div>

<div id="tap-target-documentation" class="tap-target" data-activates="btn-documentation">
    <div class="tap-target-content right-align white-text">
        <h4>Hi! You're new?</h4>
        <p>
            It seems it is the first time you're on this website.
            <br>
            You should <b>read the documentation</b>!
        </p>
    </div>
</div>