<div id="modal-documentation" class="modal modal-fixed-footer">
    <div class="modal-content">
        <h4>Documentation</h4>
        <div class="content">
            <p>Please wait until the documentation is full loaded...</p>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
</div>

<div class="fixed-action-btn">
    <a href="#modal-documentation" id="btn-documentation" class="btn-floating btn-large orange modal-trigger tooltipped" data-position="left"
       data-tooltip="Documentation">
        <i class="large material-icons">info</i>
    </a>
</div>

<div id="tap-target-documentation" class="tap-target" data-activates="btn-documentation">
    <div class="tap-target-content right-align white-text">
        <h4>Hi! You're new?</h4>
        <p>
            It seems it is the first time you're on this website.
            <br>
            You should <b>read the documentation</b>!
        </p>
    </div>
</div>