<div id="modal-legal" class="modal modal-fixed-footer">
    <div class="modal-content">
        <h4>Legal and terms of uses</h4>

        <h5>Hosting</h5>
        <p>
            This application is hosted by <a href="https://www.ovh.com">OVH</a>.
            <br>
            2 rue Kellermann
            <br>
            59100 Roubaix - France
        </p>

        <h5>Administrator</h5>
        <p>
            This application and the PhpUnitGen package were created and are maintained by <a href="https://github.com/paul-thebaud">Paul Thébaud</a>.
        </p>

        <h5>Licence and terms of use</h5>
        <p>
            MIT License
            <br><br>
            Copyright (c) 2017 Thébaud Paul
            <br><br>
            Permission is hereby granted, free of charge, to any person obtaining a copy
            of this software and associated documentation files (the "Software"), to deal
            in the Software without restriction, including without limitation the rights
            to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
            copies of the Software, and to permit persons to whom the Software is
            furnished to do so, subject to the following conditions:
            <br><br>
            The above copyright notice and this permission notice shall be included in all
            copies or substantial portions of the Software.
            <br><br>
            THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
            AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
            LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
            OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
            SOFTWARE.
        </p>
    </div>
    <div class="modal-footer">
        <button type="button" class="modal-action modal-close btn waves-effect waves-light">Close</button>
    </div>
</div>