<h3>About PhpUnitGen</h3>

<p>
    PhpUnitGen is an <b>online</b> or <b>terminal</b> development tool
    for generating your unit test skeletons for PHP code.
    It uses <i>PHPUnit 7</i> and <i>PHP 7.1</i>.
    <br>
    <br>
    This open source project begins during <b>summer 2017</b>.
    <br>
    <br>
    Since the 2.x.x version is available, some people are starting speaking about PhpUnitGen.
    <br>
    Here are all articles about the project:
</p>
<ul class="browser-default">
    <li>
        <a href="https://dev.to/paulthebaud/phpunitgen-simplify-the-writing-of-your-unit-tests--4nec" target="_blank">
            An article on dev.to, written by Paul Thébaud [EN]
            <sup><i class="material-icons tiny">open_in_new</i></sup>
        </a>
    </li>
    <li>
        <a href="/fr/article.html">
            The same article, in french version [FR]
        </a>
    </li>
</ul>
<div class="card blue lighten-2">
    <div class="card-content">
        <h5><i class="material-icons left">info</i>Notice</h5>
        <p>
            If you like PhpUnitGen, share it!
        </p>
    </div>
</div>
