<h3>PhpUnitGen</h3>

<?php include __DIR__ . '/../partial/badges.phtml'; ?>

<h3>English documentation</h3>

<div class="card orange lighten-2">
    <div class="card-content">
        <h5><i class="material-icons left">warning</i>Note</h5>
        <p>
            <b>DO NOT FORGET</b> to check each generated tests! PhpUnitGen
            will show you the place to check or edit with multiple <i>PHPDoc</i>
            <code>@todo</code> annotations.
        </p>
    </div>
</div>

<p>
    <b>Hey!</b>
    <br>
    <br>
    Welcome on the <b>english documentation</b> of PhpUnitGen.
    <br>
    <br>
    You can find <b>many information</b> here!
</p>
<ul class="browser-default">
    <li>An "<b>about</b>" page with information and articles about PhpUnitGen.</li>
    <li>A short documentation on <b>web application</b> usage.</li>
    <li>A documentation on <b>command line</b> usage (with the <i>Composer</i> package).</li>
    <li>A documentation with <b>PHP code</b> usage (with the <i>Composer</i> package).</li>
    <li>A documentation about PhpUnitGen <b>annotations</b>.</li>
</ul>
<p>
    <b>Check the links on the left (top on mobile), good reading!</b>
</p>
<br>
<p>
    Some useful links :
</p>
<ul class="browser-default">
    <li>
        <a href="https://github.com/paul-thebaud/phpunit-generator" target="_blank">
            Composer package link <sup><i class="material-icons tiny">open_in_new</i></sup>
        </a>
    </li>
    <li>
        <a href="https://github.com/paul-thebaud/phpunit-generator-website" target="_blank">
            Web application source link <sup><i class="material-icons tiny">open_in_new</i></sup>
        </a>
    </li>
</ul>
<br>
<br>
<p class="center-align" style="font-weight: bold">
    <a href="https://github.com/paul-thebaud/phpunit-generator/stargazers" target="_blank">
        You wan't to help? Stars the project on GitHub! <sup><i class="material-icons tiny">open_in_new</i></sup>
    </a>
</p>
