<h3>Installation</h3>

<p>
    Best way to install PhpUnitGen is through <i>Composer</i>. It will allow you to get update easily.
    <br>
    <i>Composer</i> is the package manager for PHP project.
</p>

<pre><code class="bash language-bash">
$ composer require --dev paulthebaud/phpunit-generator ^2.0
</code></pre>

<p>
    The <code>--dev</code> option is used to install the package only in development environment.
    <br>
    PhpUnitGen use <i>PHP 7.1</i>, but is also compatible (and tested with <i>Travis</i>) with <i>PHP 7.2</i>.
</p>

<h4>Next step</h4>

<p>
    Now you know how to install PhpUnitGen package,
    <a href="/<?= $language ?>/terminal.html">learn more on how to use it on command line</a>.
</p>
