<h3>Web application</h3>

<p>
    PhpUnitGen can be used <b>online</b>, because it parse the PHP code
    instead of using PHP Reflections.
    <br>
    <br>
    Like many other tools, it <b>can be configure</b> in it operation or it design.
    <br>
    <b>Thanks to the configuration button</b> - in top right corner when you are in the application -
    you can change those parameters:
</p>
<ul class="browser-default">
    <li><b>Editor height</b>: allow to change the PHP editor height.</li>
    <li><b>Theme</b>: allow to change the application colors (in addition, there are surprises when you use the application 🦄).</li>
    <li><b>Automatic generation</b>: allow to automatically generate unit tests for getters / setters methods, or instantiate classes or traits.</li>
    <li><b>Private / protected methods parsing</b>: allow to activate / disable the skeletons generation for private or protected methods.</li>
    <li><b>Interface parsing</b>: allow to activate / disable the skeleton generation for PHP interface.</li>
    <li><b>Generated tests PHPDoc</b>: allow to manage a list of <i>PHPDoc</i> annotations (<code>@author</code> for example) that will be added to the tests class header.</li>
</ul>
<div class="card blue lighten-2">
    <div class="card-content">
        <h5><i class="material-icons left">info</i>Notice</h5>
        <p>
            This configuration will be <b>automatically saved</b> each time it is updated, directly in your browser
            storage.
            It is possible to <b>reset it with the "reset" button</b>, in the bottom left corner of the configuration page.
        </p>
    </div>
</div>
<br>
<p>
    The web application can be used with two solutions:
</p>
<ul class="browser-default">
    <li>You can <b>import a PHP file</b>.</li>
    <li>You can use the <b>PHP code editor</b> (remember that you can give a <b>name to the generated class</b>, in the <b>field above the editor</b>).</li>
</ul>
<br>
<p>
    Finally, when you are <b>on this documentation</b>, you can click on <b>the bottom link of the menu</b>
    to go on the <b>PhpUnitGen application</b>.
</p>

<h4>Next step</h4>

<p>
    Now you know how to use PhpUnitGen on the web application,
    <a href="/<?= $language ?>/annotations.html">learn more on PhpUnitGen annotations</a>.
</p>
