<div id="share-buttons" class="fixed-action-btn horizontal">
    <a class="btn-floating btn-large orange">
        <i class="large material-icons">share</i>
    </a>
    <ul>
        <li>
            <a href="https://twitter.com/share?url=https://phpunitgen.io&text=PhpUnitGen&hashtags=phpunitgen"
               class="btn-floating">
                <img src="https://simplesharebuttons.com/images/somacro/twitter.png" alt="Twitter"/>
            </a>
        </li>
        <li>
            <a href="http://www.facebook.com/sharer.php?u=https://phpunitgen.io"
               class="btn-floating">
                <img src="https://simplesharebuttons.com/images/somacro/facebook.png" alt="Twitter"/>
            </a>
        </li>
        <li>
            <a href="https://plus.google.com/share?url=https://phpunitgen.io"
               class="btn-floating">
                <img src="https://simplesharebuttons.com/images/somacro/google.png" alt="Twitter"/>
            </a>
        </li>
        <li>
            <a href="http://www.linkedin.com/shareArticle?mini=true&url=https://phpunitgen.io"
               class="btn-floating">
                <img src="https://simplesharebuttons.com/images/somacro/linkedin.png" alt="Twitter"/>
            </a>
        </li>
    </ul>
</div>
