<?php $translations = \PhpUnitGen\Website\Language\Language::LANGUAGES[$language]; ?>

<ul id="slide-out" class="side-nav fixed">
    <li class="<?= $page === 'index' ? 'active' : '' ?>">
        <a href="/<?= $language ?>"
           class="waves-effect">
            <i class="material-icons left">home</i>
            <?= $translations['home'] ?>
        </a>
    </li>
    <li class="<?= $page === 'about' ? 'active' : '' ?>">
        <a href="/<?= $language ?>/about.html"
           class="waves-effect">
            <i class="material-icons left">info</i>
            <?= $translations['about'] ?>
        </a>
    </li>
    <li>
        <div class="divider"></div>
    </li>
    <li>
        <a class="subheader"><?= $translations['header'] ?></a>
    </li>
    <li class="<?= $page === 'installation' ? 'active' : '' ?>">
        <a href="/<?= $language ?>/installation.html"
           class="waves-effect">
            <i class="material-icons left">file_download</i>
            <?= $translations['installation'] ?>
        </a>
    </li>
    <li class="<?= $page === 'website' ? 'active' : '' ?>">
        <a href="/<?= $language ?>/website.html"
           class="waves-effect">
            <i class="material-icons left">laptop</i>
            <?= $translations['website'] ?>
        </a>
    </li>
    <li class="<?= $page === 'terminal' ? 'active' : '' ?>">
        <a href="/<?= $language ?>/terminal.html"
           class="waves-effect">
            <i class="material-icons left">featured_play_list</i>
            <?= $translations['terminal'] ?>
        </a>
    </li>
    <li class="<?= $page === 'php' ? 'active' : '' ?>">
        <a href="/<?= $language ?>/php.html"
           class="waves-effect">
            <i class="material-icons left">keyboard</i>
            <?= $translations['php'] ?>
        </a>
    </li>
    <li class="<?= $page === 'annotations' ? 'active' : '' ?>">
        <a href="/<?= $language ?>/annotations.html"
           class="waves-effect">
            <i class="char-as-icon">@</i>
            <?= $translations['annotations'] ?>
        </a>
    </li>
    <li>
        <div class="divider"></div>
    </li>
    <li>
        <a class="subheader"><?= $translations['language'] ?></a>
    </li>
    <?php foreach (\PhpUnitGen\Website\Language\Language::LANGUAGES as $languageKey => $currentLanguage): ?>
        <li>
            <a href="/<?= $languageKey ?><?= $page === 'index' ? '' : ('/' . $page . '.html') ?>" class="waves-effect">
                <?= $currentLanguage[$languageKey] ?><?php if($language === $languageKey): ?>
                    <i class="material-icons right">check_circle</i><?php endif; ?>
            </a>
        </li>
    <?php endforeach; ?>
    <li>
        <div class="divider"></div>
    </li>
    <li>
        <a class="subheader">PhpUnitGen</a>
    </li>
    <li>
        <a href="<?= $this->getAttribute(\PhpUnitGen\Website\Middleware\ResourceMiddleware::RESOURCE_APP) ?>"
           class="waves-effect"><i class="material-icons left">play_arrow</i> <?= $translations['back'] ?></a>
    </li>
</ul>
