<section id="code-editor" style="display: none">
    <h4>
        Tests from code
    </h4>
    <form class="row">
        <div class="col s12">
            <textarea id="code-textarea"><?php $content =  <<<EOF
<?php

class Person
{
    protected \$name;
    protected \$age = 0;
    
    public function __construct(string \$name)
    {
        \$this->setName(\$name);
    }
    
    /**
     * @PHPUnitGen\AssertEquals('I\'m A simple string and I\'m 0.')
     */
    public function __toString()
    {
        return 'I\'m "' . \$this->name . '" and I\'m ' . \$this->age . '.';
    }
    
    /**
     * @PHPUnitGen\Set()
     */
    public function setName(string \$name)
    {
        \$this->name = \$name;
    }
    
    /**
     * @PHPUnitGen\Get()
     */
    public function getName(): string
    {
        return \$this->name;
    }
    
    /**
     * @PHPUnitGen\AssertNotNull()
     * @PHPUnitGen\AssertEquals(1)
     */
    protected function incrementAge()
    {
        return (\$this->age += 1);
    }
}

EOF;
            echo htmlspecialchars($content);
?></textarea>
        </div>
    </form>
    <button type="button" class="left btn waves-effect blue" onclick="goToSection('#main')">
        <i class="material-icons left">arrow_back</i>Previous
    </button>
    <button type="button" class="parse right btn waves-effect waves-light orange">
        <i class="material-icons right">play_arrow</i>Generate
    </button>
</section>