<section id="code-editor" style="display: none">
    <h4>
        Tests from code
    </h4>
    <form class="row">
        <div class="col s12">
            <textarea id="code-textarea">Write your code here ...</textarea>
        </div>
    </form>
    <button type="button" class="left btn waves-effect blue" onclick="goToSection('#main')">
        <i class="material-icons left">arrow_back</i>Previous
    </button>
    <button type="button" class="parse right btn waves-effect waves-light orange">
        <i class="material-icons right">play_arrow</i>Generate
    </button>
</section>