<section id="code-editor" style="display: none">
    <h4>
        Tests from code
    </h4>
    <form class="row">
        <div class="col s12">
            <textarea id="code-textarea"><?php $content =  <<<EOF
<?php

class Person
{
    protected \$name;
    
    public function __construct(string \$name)
    {
        \$this->setName(\$name);
    }
    
    public function __toString()
    {
        return \$this->getName();
    }
    
    public function setName(string \$name)
    {
        \$this->name = \$name;
    }
    
    public function getName(): string
    {
        return \$this->name;
    }
    
    public function doSomething()
    {
        echo \$this->__toString();
    }
}

EOF;
            echo htmlspecialchars($content);
?></textarea>
        </div>
    </form>
    <button type="button" class="left btn waves-effect blue" onclick="goToSection('#main')">
        <i class="material-icons left">arrow_back</i>Previous
    </button>
    <button type="button" class="parse right btn waves-effect waves-light orange">
        <i class="material-icons right">play_arrow</i>Generate
    </button>
</section>