<h4>Website usage</h4>
<div class="divider"></div>
<br>

This website provide a full configuration of PhpUnitGen:
<ul style="list-style-type:circle">
    <li>PHP editor height.</li>
    <li>Application theme.</li>
    <li>Automatic generation (generate getter and setter tests, and class instantiation).</li>
    <li>Interfaces parsing (if interfaces should be parsed too).</li>
    <li>Private / protected methods parsing (if private / protected methods should be parsed too).</li>
    <li>PHPDoc annotations: a list of annotations that should be include in your tests class header documentation</li>
</ul>

<h4>Annotations usage</h4>
<div class="divider"></div>
<br>

<?php
$mdDocumentation = file_get_contents('https://raw.github.com/paul-thebaud/phpunit-generator/develop/documentation/ANNOTATIONS.md');
$mdDocumentation = preg_replace('/^.+\n/', '', $mdDocumentation);

echo Parsedown::instance()->text($mdDocumentation);
?>
