<h1>PhpUnitGen - Website</h1>

This website provide a full configuration of PhpUnitGen:
<ul style="list-style-type:circle">
    <li>PHP editor height.</li>
    <li>Application theme.</li>
    <li>Automatic generation (generate getter and setter tests, and class instantiation).</li>
    <li>Interface parsing (if interface should be parsed too).</li>
    <li>Private / protected methods parsing (if private / protected methods should be parsed too).</li>
    <li>PHPDoc annotations: a list of annotations that should be include in your tests class header documentation</li>
</ul>



<?=
Parsedown::instance()
    ->text(file_get_contents('https://raw.github.com/paul-thebaud/phpunit-generator/develop/documentation/ANNOTATIONS.md'));
?>
