<section id="main" class="center-align">
    <h4>A simple tool to generate your unit tests skeleton!</h4>

    <!-- File input -->
    <label class="btn-large waves-effect waves-light orange">
        <input name="file" type="file"/>
        <i class="material-icons left">file_upload</i>Upload your file
    </label>
    <h5>OR</h5>
    <!-- Code editor open -->
    <button type="button" class="btn-large waves-effect waves-light orange" onclick="goToSection('#code-editor')">
        <i class="material-icons left">mode_edit</i>Write your code
    </button>
</section>