<section id="modals">
    <div id="modal-config" class="modal">
        <div class="modal-content">
            <h4>Settings</h4>
            <div class="row">
                <div class="col s12 l6">
                    <b>Automatic getters / setters tests</b>
                </div>
                <div class="col s12 l6 switch">
                    <label>
                        Off
                        <input name="auto" type="checkbox">
                        <span class="lever"></span>
                        On
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="col s12 l6">
                    <b>Author</b>
                </div>
                <div class="col s12 l6">
                    <input name="doc-author" placeholder="John Doe <john.doe@example.com>">
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="modal-action modal-close btn waves-effect waves-light blue">Close</button>
        </div>
    </div>
    <div id="modal-documentation" class="modal">
        <div class="modal-content">
            <?= file_get_contents(__DIR__ . '/../documentation.html') ?>
        </div>
        <div class="modal-footer">
            <button type="button" class="modal-action modal-close btn waves-effect waves-light blue">Close</button>
        </div>
    </div>
</section>