<section id="modals">
    <div id="modal-config" class="modal">
        <div class="modal-content">
            <h4>Settings</h4>
            <p>
                Customize your settings here, they will be saved each times you change them.
            </p>
        </div>
        <div id="design-settings" class="settings">
            <div class="divider"></div>
            <div class="setting">
                <div class="row valign-wrapper">
                    <div class="col s12 l6 left">
                        <span>Dark theme</span>
                    </div>
                    <div class="col s12 l6 right">
                        <div class="switch">
                            <label>
                                <input id="dark-theme-switch" name="dark-theme" type="checkbox">
                                <span class="lever"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="generation-settings" class="settings">
            <div class="divider"></div>
            <div class="setting">
                <div class="row valign-wrapper">
                    <div class="col s12 l6 left">
                        <span>Automatic getters / setters tests</span>
                    </div>
                    <div class="col s12 l6 right">
                        <div class="switch">
                            <label>
                                <input name="auto" type="checkbox">
                                <span class="lever"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="divider"></div>
            <div class="setting">
                <div class="row valign-wrapper">
                    <div class="col s12 l6 left">
                        <span>Author (PHPDoc)</span>
                    </div>
                    <div class="col s12 l6 right">
                        <input name="doc-author" type="text" placeholder="John Doe <john.doe@example.com>">
                    </div>
                </div>
                <div class="row valign-wrapper">
                    <div class="col s12 l6 left">
                        <span>Copyright (PHPDoc)</span>
                    </div>
                    <div class="col s12 l6 right">
                        <input name="doc-copyright" type="text" placeholder="2016 - <?= date('Y') ?> John Doe">
                    </div>
                </div>
                <div class="row valign-wrapper">
                    <div class="col s12 l6 left">
                        <span>Licence (PHPDoc)</span>
                    </div>
                    <div class="col s12 l6 right">
                        <input name="doc-licence" type="text" placeholder="http://opensource.org/licenses/gpl-license.php GNU Public License">
                    </div>
                </div>
                <div class="row valign-wrapper">
                    <div class="col s12 l6 left">
                        <span>Since (PHPDoc)</span>
                    </div>
                    <div class="col s12 l6 right">
                        <input name="doc-since" type="text" placeholder="1.34.5">
                    </div>
                </div>
            </div>
            <div class="divider"></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="modal-action modal-close btn waves-effect waves-light blue">Close</button>
        </div>
    </div>
    <div id="modal-documentation" class="modal">
        <div class="modal-content">
            <?= file_get_contents(__DIR__ . '/../documentation.html') ?>
        </div>
        <div class="modal-footer">
            <button type="button" class="modal-action modal-close btn waves-effect waves-light blue">Close</button>
        </div>
    </div>
    <div id="modal-legal" class="modal">
        <div class="modal-content">
            <?= file_get_contents(__DIR__ . '/../legal.html') ?>
        </div>
        <div class="modal-footer">
            <button type="button" class="modal-action modal-close btn waves-effect waves-light blue">Close</button>
        </div>
    </div>
    <div id="modal-clear-confirm" class="modal">
        <div class="modal-content">
            <h4>We need your confirmation!</h4>
            <p>
                Do you confirm you want to refresh the page and clear all forms?
            </p>
        </div>
        <div class="modal-footer">
            <a href="" class="btn waves-effect waves-light red">Confirm</a>
            <button type="button" class="modal-action modal-close btn waves-effect waves-light blue">Close</button>
        </div>
    </div>
</section>