<section id="tab-main">
    <div class="row">
        <div class="col s12">
            <h3>A simple tool to generate your unit tests skeleton!</h3>

            <!-- File input -->
            <label class="btn-large waves-effect waves-light orange">
                <input id="file-import" name="file" type="file"/>
                <i class="material-icons left">file_upload</i>Upload your file
            </label>
            <h4>OR</h4>
            <!-- Code editor open -->
            <button type="button" class="btn-large btn-tab waves-effect waves-light orange"
                    data-source="main" data-target="code-editor" data-direction="right">
                <i class="material-icons left">mode_edit</i>Write your code
            </button>
        </div>
    </div>
</section>