<section id="tab-code-editor" style="display: none;">
    <div class="row valign-wrapper">
        <div class="col s2">
            <button type="button" class="btn-floating btn-large btn-tab orange tooltipped"
                    data-position="right" data-duration="50" data-tooltip="Go to the home page"
                    data-source="code-editor" data-target="main" data-direction="left">
                <i class="material-icons">home</i>
            </button>
        </div>
        <div class="col s8">
            <h3>Your PHP code is here...</h3>

            <div class="input-field" style="margin-top: 30px">
                <input placeholder="MyClassNameTest" id="name" name="name" type="text">
                <label for="name">Choose a name for your tests class (optional, default is "GeneratedTest")</label>
            </div>

            <div class="left-align">
                <textarea id="code-editor-textarea" name="code-editor-textarea"></textarea>
                <div id="code-editor-content" style="display: none"><?=
                    file_get_contents(__DIR__ . '/../examples/code.txt')
                    ?></div>
            </div>
        </div>
        <div class="col s2">
            <button id="btn-generate" type="button" class="btn-floating btn-large btn-tab orange tooltipped"
                    data-position="left" data-duration="50" data-tooltip="Launch generation!"
                    data-source="code-editor" data-target="tests-editor" data-direction="right">
                <i class="material-icons">play_arrow</i>
            </button>
        </div>
    </div>
</section>