<section id="tests-editor" style="display: none">
    <h4>
        Your generated tests
    </h4>
    <form class="row">
        <div class="col s12">
            <textarea id="tests-textarea">Oups, why do you see this text here ... Maybe report and issues</textarea>
        </div>
    </form>
    <button type="button" class="previous left btn waves-effect blue">
        <i class="material-icons left">arrow_back</i>Previous
    </button>

    <button type="button" class="download right btn waves-effect waves-light orange tooltipped"
            data-tooltip="Download as a file">
        <i class="material-icons">file_download</i>
    </button>
    <button type="button" class="copy right btn waves-effect waves-light orange tooltipped"
            data-tooltip="Copy to clipboard" style="margin-right: 10px;">
        <i class="material-icons">content_copy</i>
    </button>
    <button type="button" class="rerun right btn waves-effect waves-light orange tooltipped"
            data-tooltip="Rerun generation" style="margin-right: 10px;">
        <i class="material-icons">refresh</i>
    </button>
</section>