<div id="global-mobile" class="hide-on-med-and-up valign-wrapper" style="display: none">
    <div class="container">
        <div class="center-align white-text">
            <p class="flow-text">
                Sorry about that, but this website <b>is not responsive</b>.
                <br>
                Because it will be <b>useless to generate PHPUnit tests on mobile</b>.
                <br>
                <br>
                If you want to visit it anyway, just click on the button.
                <br>
                It will not display this message anymore.
                <br>
                <br>
                <button type="button" id="btn-visit-mobile" class="btn waves-effect waves-light orange">
                    Ok, let's display it!
                </button>
            </p>
        </div>
    </div>
</div>