<!DOCTYPE html>
<html lang="en">

<?php require_once __DIR__ . '/../partial/header.phtml'; ?>

<body>

<div id="global">

    <main class="valign-wrapper">

        <div class="had-container center-align">

            <img src="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/logo.svg?sanitize=true"
                 width="300px" style="margin: auto">

            <h3>404 not found...</h3>

            <p><b>How did you get here?!<br><br><a href="/">Back to home page!</a></b></p>

        </div>

    </main>

</div>

</body>

</html>
