<footer class="page-footer blue">
    <div class="container">
        <div class="row">
            <div class="col l8 s12">
                <h5 class="white-text">About</h5>
                <p>
                    PHPUnit Generator is a simple tool to generate your unit tests skeleton.
                    <br>
                    It only needs the file you want to generate tests for, because it uses PHP parsing.
                    <br>
                    It does not save your file, it just read it one times to parse it.
                </p>
            </div>
            <div class="col l4 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li>
                        <a class="white-text" href="https://github.com/paul-thebaud/phpunit-generator">
                            Package source
                        </a>
                    </li>
                    <li>
                        <a class="white-text" href="https://github.com/paul-thebaud/phpunit-generator/issues">
                            Report an issue
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Copyright &copy; <?= date('Y') ?>
            <a class="white-text" href="https://github.com/paul-thebaud" target="_blank"><b>Paul Thébaud</b></a>.
        </div>
    </div>
</footer>
