<nav class="blue">
    <div class="nav-wrapper container">
        <a href="" class="hide-on-small-only brand-logo">PHPUnit Generator</a>
        <a href="" class="hide-on-med-and-up brand-logo">PHPUnitGen</a>

        <ul class="right hide-on-med-and-down">
            <li>
                <a href="#modal-config" class="modal-trigger"><i class="material-icons left">settings</i>CUSTOMISE</a>
            </li>
            <li>
                <a href=""><i class="material-icons left">clear</i>CLEAR</a>
            </li>
        </ul>

        <ul id="nav-mobile" class="side-nav">
            <li>
                <a href="#modal-config" class="modal-trigger"><i class="material-icons left">settings</i>CUSTOMISE</a>
            </li>
            <li>
                <a href=""><i class="material-icons left">clear</i>CLEAR</a>
            </li>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
</nav>