<!DOCTYPE html>
<html lang="en">

<?php require_once __DIR__ . '/partial/header.phtml'; ?>

<body>

<div id="global">

    <?php require_once __DIR__ . '/partial/nav.phtml'; ?>

    <main class="valign-wrapper">

        <div class="had-container center-align">

            <?php require_once __DIR__ . '/section/tab-main.phtml'; ?>

            <?php require_once __DIR__ . '/section/tab-code-editor.phtml'; ?>

            <?php require_once __DIR__ . '/section/tab-tests-editor.phtml'; ?>

        </div>

        <?php require_once __DIR__ . '/modal/documentation.phtml'; ?>

        <?php require_once __DIR__ . '/modal/legal.phtml'; ?>

        <?php require_once __DIR__ . '/modal/configuration.phtml'; ?>

        <?php require_once __DIR__ . '/modal/confirm-reset.phtml'; ?>

        <?php require_once __DIR__ . '/partial/floating-button.phtml'; ?>

    </main>

    <?php require_once __DIR__ . '/partial/spinner.phtml'; ?>

    <?php require_once __DIR__ . '/partial/footer.phtml'; ?>

</div>

</body>

</html>
