<div id="cookie-law-container" class="blue-grey darken-3 white-text z-depth-5" style="display: none;">
    <div class="center-align">
        <div class="cookie-law-container-sub">
            <span class="cookie-law-title">This website uses cookies to give you the best experience.</span>
            <br>
            <span>By clicking anywhere, you will accept our cookie policy.</span>
        </div>
        <div class="cookie-law-container-sub">
            <a href="https://www.cookielaw.org/the-cookie-law/" class="btn waves-effect waves-light" target="_blank">
                Tell me more
            </a>
            &nbsp;
            <button id="btn-accept-cookie" type="button" class="btn waves-effect waves-light orange">It's okay!</button>
        </div>
    </div>
</div>