<div id="cookie-law-container" class="footer-copyright grey darken-4 white-text" style="display: none;">
    <div class="container">
        <div class="row valign-wrapper">
            <div class="col s7 left-align">
                <b>This website uses cookies to give you the best experience.</b>
                <br>
                <span>By clicking anywhere, you will accept our cookie policy.</span>
            </div>
            <div class="col s5 right-align">
                <a href="https://www.cookielaw.org/the-cookie-law/" class="btn waves-effect waves-light"
                   target="_blank">Tell me more</a>
                &nbsp;
                <button id="btn-accept-cookie" type="button" class="btn waves-effect waves-light orange">It's okay!
                </button>
            </div>
        </div>
    </div>
</div>