<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

    <!-- Title and description -->
    <title>PhpUnitGen</title>
    <meta name="description"
          content="PhpUnitGen is a simple development tool that generate your PHPUnit tests skeletons from your PHP code"/>

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" content="PhpUnitGen"/>
    <meta name="twitter:description" content="A simple dev tool to generate your PHPUnit tests skeletons"/>
    <meta name="twitter:image" content="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/favicons/favicon_base.png"/>

    <!-- Open Graph data -->
    <meta property="og:title" content="PhpUnitGen"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://phpunitgen.io/"/>
    <meta property="og:image" content="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/favicons/favicon_base.png"/>
    <meta property="og:description" content="A simple dev tool to generate your PHPUnit tests skeletons"/>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/apple-touch-icon.png"/>
    <link rel="icon" type="image/png" sizes="32x32"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/favicon-32x32.png"/>
    <link rel="icon" type="image/png" sizes="16x16"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/favicon-16x16.png"/>
    <link rel="manifest"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/site.webmanifest"/>
    <link rel="mask-icon"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/safari-pinned-tab.svg?sanitize=true"
          color="#5bbad5"/>
    <link rel="shortcut icon"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/favicon.ico"/>
    <meta name="msapplication-TileColor" content="#2d89ef"/>
    <meta name="msapplication-config"
          content="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/browserconfig.xml"/>
    <meta name="theme-color" content="#2196f3"/>

    <!-- Materialize icons -->
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
    <!-- CodeMirror  -->
    <link type="text/css" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/codemirror.min.css"/>
    <link type="text/css" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/theme/monokai.min.css"/>
    <link type="text/css" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/addon/display/fullscreen.css"/>
    <!-- App style -->
    <link type="text/css" rel="stylesheet" href="assets/css/app.css"/>
    <!-- Prism -->
    <link type="text/css" rel="stylesheet" href="assets/css/prism.monokai.css"/>
</head>