<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

    <title>PhpUnitGen</title>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/favicon-16x16.png">
    <link rel="manifest"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/site.webmanifest">
    <link rel="mask-icon"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/safari-pinned-tab.svg?sanitize=true"
          color="#5bbad5">
    <link rel="shortcut icon"
          href="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/favicon.ico">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="msapplication-config"
          content="https://github.com/paul-thebaud/phpunit-generator-assets/raw/master/logos/favicons/icons/browserconfig.xml">
    <meta name="theme-color" content="#2196f3">

    <!-- Materialize icons -->
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <!-- CodeMirror  -->
    <link type="text/css" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/codemirror.min.css">
    <link type="text/css" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/theme/monokai.min.css">
    <link type="text/css" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/addon/display/fullscreen.css">

    <!-- App style -->
    <link type="text/css" rel="stylesheet" href="assets/css/app.css"/>

    <!-- Prism -->
    <link type="text/css" rel="stylesheet" href="assets/css/prism.monokai.css"/>
</head>