<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

    <title>PhpUnitGen</title>

    <link rel="icon" type="image/png" href="/assets/img/favicon.png"/>

    <!-- Materialize icons -->
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <!-- CodeMirror  -->
    <link type="text/css" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/codemirror.min.css">
    <link type="text/css" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/theme/monokai.min.css">
    <link type="text/css" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/addon/display/fullscreen.css">

    <!-- App style -->
    <link type="text/css" rel="stylesheet" href="assets/css/app.css"/>
</head>