<nav class="blue">
    <div class="nav-wrapper container">
        <a href="" class="brand-logo valign-wrapper">
            <img class="responsive-img"
                 src="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/light_logo.svg?sanitize=true">
        </a>

        <ul class="right hide-on-med-and-down">
            <li>
                <a href="#modal-configuration" class="modal-trigger">
                    <i class="material-icons left">settings</i>Settings
                </a>
            </li>
        </ul>
    </div>
</nav>