<nav class="blue">
    <div class="nav-wrapper container">
        <a href="" class="brand-logo valign-wrapper left">
            <img class="responsive-img" alt="PhpUnitGen"
                 src="https://raw.github.com/paul-thebaud/phpunit-generator-assets/master/logos/light_logo.svg?sanitize=true">
        </a>
        <ul class="right">
            <li>
                <a href="#modal-configuration" class="modal-trigger">
                    <i class="material-icons left">settings</i><span class="hide-on-small-only">Settings</span>
                </a>
            </li>
        </ul>
    </div>
</nav>