<!-- Jquery -->
<script type="application/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="application/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<!-- CodeMirror -->
<script type="application/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/codemirror.min.js"></script>
<script type="application/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/mode/htmlmixed/htmlmixed.min.js"></script>
<script type="application/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/mode/javascript/javascript.min.js"></script>
<script type="application/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/mode/xml/xml.min.js"></script>
<script type="application/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/mode/clike/clike.min.js"></script>
<script type="application/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/mode/php/php.min.js"></script>
<script type="application/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/addon/display/fullscreen.js"></script>
<!-- Materialize -->
<script type="application/javascript" src="assets/js/materialize.min.js"></script>
<!-- App -->
<script type="application/javascript" src="assets/js/app.loader.js"></script>