<!-- Routes and domain -->
<script type="application/javascript">
    var URL_API = '<?= $this->getAttribute(\PhpUnitGen\Website\Middleware\ResourceMiddleware::RESOURCE_API) ?>';
</script>
<!-- Jquery -->
<script type="application/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="application/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<!-- Materialize -->
<script type="application/javascript" src="/assets/js/materialize.min.js"></script>
<!-- Cookie message shower -->
<script type="application/javascript" src="/assets/js/app.cookie.js" onload="PhpUnitGenCookieLaw.initialize();"></script>
<!-- Prism -->
<script type="application/javascript" src="/assets/js/prism.min.js"></script>
<!-- App common -->
<script type="application/javascript" src="/assets/js/app.common.js"></script>
<?php if (isset($isApp)): ?>
    <!-- CodeMirror -->
    <script type="application/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/codemirror.min.js"></script>
    <script type="application/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/mode/htmlmixed/htmlmixed.min.js"></script>
    <script type="application/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/mode/javascript/javascript.min.js"></script>
    <script type="application/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/mode/xml/xml.min.js"></script>
    <script type="application/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/mode/clike/clike.min.js"></script>
    <script type="application/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/mode/php/php.min.js"></script>
    <script type="application/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.10.0/addon/display/fullscreen.js"></script>
    <!-- Clipboard -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js"></script>
    <!-- App -->
    <script type="application/javascript" src="/assets/js/app.loader.js"></script>
<?php endif; ?>
