<!DOCTYPE html>
<html lang="en">

<?php include __DIR__ . '/../layout/header.phtml'; ?>

<body>

<div id="global">
    <?php include __DIR__ . '/../layout/partial/nav.phtml'; ?>

    <main class="container">

        <?php if (isset($language)): ?>
        <?php $translations = \PhpUnitGen\Website\Language\Language::LANGUAGES[$language]; ?>
        <div class="row">
            <div class="col s12 m4 l4 xl3">
                <div class="collection with-header card">
                    <a href="/<?= $language ?>"
                       class="collection-item<?= $page === 'index' ? ' active' : '' ?>">
                        <?= $translations['home'] ?>
                    </a>
                    <a href="/<?= $language ?>/about.html"
                       class="collection-item<?= $page === 'about' ? ' active' : '' ?>">
                        <?= $translations['about'] ?>
                    </a>
                    <h5 class="collection-header"><?= $translations['header'] ?></h5>
                    <a href="/<?= $language ?>/website.html"
                       class="collection-item<?= $page === 'website' ? ' active' : '' ?>">
                        <?= $translations['website'] ?>
                    </a>
                    <a href="/<?= $language ?>/terminal.html"
                       class="collection-item<?= $page === 'terminal' ? ' active' : '' ?>">
                        <?= $translations['terminal'] ?>
                    </a>
                    <a href="/<?= $language ?>/php.html"
                       class="collection-item<?= $page === 'php' ? ' active' : '' ?>">
                        <?= $translations['php'] ?>
                    </a>
                    <a href="/<?= $language ?>/annotations.html"
                       class="collection-item<?= $page === 'annotations' ? ' active' : '' ?>">
                        <?= $translations['annotations'] ?>
                    </a>
                    <h5 class="collection-header">Language</h5>
                    <a href="/en<?= $page === 'index' ? '' : ('/' . $page . '.html') ?>" class="collection-item">English</a>
                    <a href="/fr<?= $page === 'index' ? '' : ('/' . $page . '.html') ?>" class="collection-item">Français</a>
                </div>
            </div>
            <div class="col s12 m8 l8 xl9">
                <div class="card">
                    <div class="card-content">
                        <?php include __DIR__ . '/' . $view ?>
                    </div>
                </div>
            </div>
        </div>
        <?php else: ?>
            <?php include __DIR__ . '/' . $view; ?>
        <?php endif; ?>

    </main>

    <?php include __DIR__ . '/../layout/partial/footer.phtml'; ?>
</div>

<div class="fixed-action-btn">
    <a href="<?= $this->getAttribute(\PhpUnitGen\Website\Middleware\ResourceMiddleware::RESOURCE_APP) ?>"
       id="btn-documentation" class="btn-floating btn-large orange tooltipped"
       data-position="left" data-duration="50" data-tooltip="Back to PhpUnitGen!">
        <i class="large material-icons">play_arrow</i>
    </a>
</div>

<?php include __DIR__ . '/../layout/partial/legal.phtml'; ?>

<?php include __DIR__ . '/../layout/scripts.phtml'; ?>

</body>

</html>
