<!DOCTYPE html>
<html lang="en">

<?php include __DIR__ . '/../layout/header.phtml'; ?>

<body>

<div id="global" class="hasSidebar">
    <?php include __DIR__ . '/../layout/partial/nav.phtml'; ?>

    <?php include __DIR__ . '/partial/sidenav.phtml'; ?>

    <main>
        <div class="row">
            <div class="col s12 l10 xl9" style="padding: 20px">
                <?php include __DIR__ . '/' . $view ?>
            </div>
        </div>

        <div class="row">
            <div class="col s12 center-align">
                <?php include __DIR__ . '/partial/share.phtml'; ?>
            </div>
        </div>

    </main>

    <?php include __DIR__ . '/partial/footer.phtml'; ?>
</div>

<?php include __DIR__ . '/../layout/partial/legal.phtml'; ?>

<?php include __DIR__ . '/../layout/scripts.phtml'; ?>

<script type="application/javascript">
    $(document).ready(function () {
        $("#btn-sidenav").sideNav();
    });
</script>

</body>

</html>
